# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gRPC import ClientgRPC_pb2 as gRPC_dot_ClientgRPC__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gRPC/ClientgRPC_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveGlobalModel = channel.unary_unary(
                '/fl_client.ClientService/ReceiveGlobalModel',
                request_serializer=gRPC_dot_ClientgRPC__pb2.ReceiveGlobalModelRequest.SerializeToString,
                response_deserializer=gRPC_dot_ClientgRPC__pb2.ReceiveGlobalModelResponse.FromString,
                _registered_method=True)
        self.ReceiveModelForAccuracyBasedMeasure = channel.unary_unary(
                '/fl_client.ClientService/ReceiveModelForAccuracyBasedMeasure',
                request_serializer=gRPC_dot_ClientgRPC__pb2.AccuracyBasedMeasureRequest.SerializeToString,
                response_deserializer=gRPC_dot_ClientgRPC__pb2.AccuracyBasedMeasureResponse.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveGlobalModel(self, request, context):
        """1. Receive global model from server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveModelForAccuracyBasedMeasure(self, request, context):
        """2. Get trained model from client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveGlobalModel,
                    request_deserializer=gRPC_dot_ClientgRPC__pb2.ReceiveGlobalModelRequest.FromString,
                    response_serializer=gRPC_dot_ClientgRPC__pb2.ReceiveGlobalModelResponse.SerializeToString,
            ),
            'ReceiveModelForAccuracyBasedMeasure': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveModelForAccuracyBasedMeasure,
                    request_deserializer=gRPC_dot_ClientgRPC__pb2.AccuracyBasedMeasureRequest.FromString,
                    response_serializer=gRPC_dot_ClientgRPC__pb2.AccuracyBasedMeasureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fl_client.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fl_client.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl_client.ClientService/ReceiveGlobalModel',
            gRPC_dot_ClientgRPC__pb2.ReceiveGlobalModelRequest.SerializeToString,
            gRPC_dot_ClientgRPC__pb2.ReceiveGlobalModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveModelForAccuracyBasedMeasure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl_client.ClientService/ReceiveModelForAccuracyBasedMeasure',
            gRPC_dot_ClientgRPC__pb2.AccuracyBasedMeasureRequest.SerializeToString,
            gRPC_dot_ClientgRPC__pb2.AccuracyBasedMeasureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
