# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gRPC/ClientgRPC.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gRPC/ClientgRPC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gRPC/ClientgRPC.proto\x12\tfl_client\"X\n\x19ReceiveGlobalModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x14\n\x0cglobal_model\x18\x02 \x01(\x0c\x12\x12\n\nmodel_type\x18\x03 \x01(\t\"q\n\x1aReceiveGlobalModelResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63lient_model\x18\x02 \x01(\x0c\x12\x15\n\rtraining_time\x18\x03 \x01(\x02\x12\x13\n\x0biid_measure\x18\x04 \x01(\x02\"S\n\x1b\x41\x63\x63uracyBasedMeasureRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\r\n\x05model\x18\x02 \x01(\x0c\x12\x12\n\nmodel_type\x18\x03 \x01(\t\"8\n\x1c\x41\x63\x63uracyBasedMeasureResponse\x12\x18\n\x10weighted_val_acc\x18\x01 \x01(\x02\x32\xea\x01\n\rClientService\x12\x61\n\x12ReceiveGlobalModel\x12$.fl_client.ReceiveGlobalModelRequest\x1a%.fl_client.ReceiveGlobalModelResponse\x12v\n#ReceiveModelForAccuracyBasedMeasure\x12&.fl_client.AccuracyBasedMeasureRequest\x1a\'.fl_client.AccuracyBasedMeasureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC.ClientgRPC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIVEGLOBALMODELREQUEST']._serialized_start=36
  _globals['_RECEIVEGLOBALMODELREQUEST']._serialized_end=124
  _globals['_RECEIVEGLOBALMODELRESPONSE']._serialized_start=126
  _globals['_RECEIVEGLOBALMODELRESPONSE']._serialized_end=239
  _globals['_ACCURACYBASEDMEASUREREQUEST']._serialized_start=241
  _globals['_ACCURACYBASEDMEASUREREQUEST']._serialized_end=324
  _globals['_ACCURACYBASEDMEASURERESPONSE']._serialized_start=326
  _globals['_ACCURACYBASEDMEASURERESPONSE']._serialized_end=382
  _globals['_CLIENTSERVICE']._serialized_start=385
  _globals['_CLIENTSERVICE']._serialized_end=619
# @@protoc_insertion_point(module_scope)
