# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gRPC/ServergRPC.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gRPC/ServergRPC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gRPC/ServergRPC.proto\x12\tfl_server\"F\n\x19\x43lientRegistrationRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x63lient_api_url\x18\x02 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2b\n\rServerService\x12Q\n\x0eRegisterClient\x12$.fl_server.ClientRegistrationRequest\x1a\x19.fl_server.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC.ServergRPC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREGISTRATIONREQUEST']._serialized_start=36
  _globals['_CLIENTREGISTRATIONREQUEST']._serialized_end=106
  _globals['_STATUSRESPONSE']._serialized_start=108
  _globals['_STATUSRESPONSE']._serialized_end=140
  _globals['_SERVERSERVICE']._serialized_start=142
  _globals['_SERVERSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
